apiVersion: 1

# List of datasources to delete from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# List of datasources to insert/update depending
# on what's available in the database
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: GET
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: xray